In [24]:
import numpy as np
import pandas as pd
from pathlib import Path

In [25]:
pth=Path('data','lead_pipes.csv')
df=pd.read_csv(pth)
df.head()

,State,Total LSLs (high estimate),State Population,LSLs per 100k people
0,StateAlabama,"Total LSLs (high estimate) 63,000","State Population 5,024,279","LSLs per 100k people 1,254"
1,StateAlaska,"Total LSLs (high estimate) 3,800","State Population 733,391",LSLs per 100k people 518
2,StateArizona,"Total LSLs (high estimate) 12,000","State Population 7,151,502",LSLs per 100k people 168
3,StateArkansas,"Total LSLs (high estimate) 40,000","State Population 3,011,524","LSLs per 100k people 1,328"
4,StateCalifornia,"Total LSLs (high estimate) 65,000","State Population 39,538,223",LSLs per 100k people 164

In [26]:
df['State']=df['State'].str.lstrip('State')
df['Total LSLs (high estimate)']=df['Total LSLs (high estimate)'].str.lstrip('Total LSLs (high estimate)')
df['State Population']=df['State Population'].str.lstrip('State Population')
# df['LSLs per 100k people']=df['LSLs per 100k people'].str.lstrip('LSLs per 100k people')
df.head()

,State,Total LSLs (high estimate),State Population,LSLs per 100k people
0,Alabama,"63,000","5,024,279","LSLs per 100k people 1,254"
1,Alaska,"3,800","733,391",LSLs per 100k people 518
2,Arizona,"12,000","7,151,502",LSLs per 100k people 168
3,Arkansas,"40,000","3,011,524","LSLs per 100k people 1,328"
4,California,"65,000","39,538,223",LSLs per 100k people 164

In [36]:
df['Total LSLs (high estimate)']=df['Total LSLs (high estimate)'].replace(',','',regex=True)
df['State Population']=df['State Population'].replace(',','',regex=True)
df['LSLs per 100k people']=df['LSLs per 100k people'].replace('LSLs per 100k people ','',regex=True)
df['LSLs per 100k people']=df['LSLs per 100k people'].replace(',','',regex=True)
df.head()

        State Total LSLs (high estimate) State Population LSLs per 100k people
0     Alabama                      63000          5024279                 1254
1      Alaska                       3800           733391                  518
2     Arizona                      12000          7151502                  168
3    Arkansas                      40000          3011524                 1328
4  California                      65000         39538223                  164

In [46]:
df['Total LSLs (high estimate)']=pd.to_numeric(df['Total LSLs (high estimate)'])
df['State Population']=pd.to_numeric(df['State Population'])
df['LSLs per 100k people']=pd.to_numeric(df['LSLs per 100k people'])
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   State                       51 non-null     object
 1   Total LSLs (high estimate)  51 non-null     int64
 2   State Population            51 non-null     int64
 3   LSLs per 100k people        51 non-null     int64
 4   LSLs per 100k people        51 non-null     int64
dtypes: int64(4), object(1)
memory usage: 2.1+ KB

In [50]:
df.to_csv('data/lead_pipes_clean.csv',index=False)

In [51]:
df.describe()

,Total LSLs (high estimate),State Population,LSLs per 100k people,LSLs per 100k people
count,51.000000,5.100000e+01,51.000000,51.000000
mean,121170.235294,6.499006e+06,1938.960784,1938.960784
std,160157.490391,7.408023e+06,1754.549298,1754.549298
min,2800.000000,5.768510e+05,164.000000,164.000000
25%,18000.000000,1.816411e+06,924.000000,924.000000
50%,53000.000000,4.505836e+06,1176.000000,1176.000000
75%,160000.000000,7.428392e+06,2476.000000,2476.000000
max,679292.000000,3.953822e+07,5597.000000,5597.000000